### ISSUE TITLE
Creating .conllu file

### ISSUE THREAD

**Issue by vjosapreniqi** [UniversalDependencies/UD_Albanian-TSA#7]
Hello @dan-zeman, thank you for this work. I would like to know how you create .conllu file, have you used any programmable method to convert sentences into this format? I saw you have explained that for Tagging and Morphological Analysis, you have used semi-automated python scripts, and then corrected them manually. So, can you share those coding scripts with us, or explain your work briefly, from collecting the data using Wikipedia, and performing lemmatization, to creating .conllu file.

**Comment by dan-zeman** [comment]
I think this is a question for @mar-cy.

**Comment by mar-cy** [comment]
Hello @vjosapreniqi, the creation of the .conllu file was to some extent manual. More specifically, I first had the raw text (which I extracted manually from Wikipedia) in a .txt file and then tokenized it based on whitespace with a script using regex, in such a way that each token appeared on a single line, while also using full stops as delimiters for sentences, among which a new line was inserted. For the creation of the .conllu format, I created a script which inserted enumeration in front of each token (restarting after each new line) and which also created another 8 columns with underscores ("_") as placeholders. Then, by changing the extention of the file from .txt to .conllu, you basically have a .conllu file with its skeleton. 
For lemmatization, please check https://bitbucket.org/timarkh/uniparser-albanian-grammar/src/master/  which we used as well. The same team also has created a tagger and morphological analyzer for Albanian (although not UD compliant). Otherwise, I can make available on GitHub in the next days the tagger and morphological analyzer that I created for this project, although they may not be of great help at the moment as they are not very sophisticated and need to be expanded in terms of rules and lexicon terms.
I hope this helps for now, though.
